name: Check Release PR

on:
  pull_request:
    paths:
      - 'CHANGELOG.md'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  check_release_pr:
    name: Check Release PR
    if: startsWith(github.head_ref, 'chore/release/')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout faker
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: faker

      - name: Checkout playground
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: faker-js/playground
          path: playground

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          package_json_file: faker/package.json

      - name: Set node version to 22
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: |
            faker/pnpm-lock.yaml
            playground/pnpm-lock.yaml

      - name: Install deps - faker
        run: |
          cd faker
          pnpm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build - faker
        run: |
          cd faker
          pnpm run build

      - name: Install deps - playground
        run: |
          cd playground
          sed -i 's/overrides-for-release/overrides/' package.json
          pnpm install --no-frozen-lockfile

      - name: Build - playground
        run: |
          cd playground
          pnpm run build

      - name: Test - playground
        run: |
          cd playground
          pnpm run test
